server:
  port: 3381
spring:
  application:
    name: testSleuthMessaging
  sleuth:
    log:
      slf4j:
        enabled: true
    sampler: 
      percentage: 1.0
  rabbitmq:
    host: ${RABBIT_HOST:local.brother}
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    stream:
      bindings:
        input: 
          destination: testqueue
        output: 
          destination: testqueue
#spring.zipkin.baseUrl: xxx
#spring.sleuth.sampler.percentage: 0.1
# spring.zipkin.locator.discovery.enabled: true